### ISSUE TITLE
Applet crash at startup

### ISSUE THREAD

**Issue by mirceat11** [gvajda/radio-paradise-song-notification#1] opened 2020-03-03 14:50 UTC
RP_Notify.exe v1.1 crashes at startup on a Windows 10 Pro version 1909 PC.
The main suspect is the local VPN client which disables the LAN access and routes the whole traffic through the remote VPN server.
This might be a rare use case, therefore the exception handling and a graceful application shutdown would be enough, I guess.

There is no log entry for the applet startup into c:\Users<username>\AppData\Roaming\RP_Notify\log.txt.

The first entry from the Event viewer:
Application: RP_Notify.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
at RP_Notify.Config.IniConfig.SyncMemoryConfig()
at RP_Notify.Config.IniConfig..ctor()
.....
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(System.Type)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IServiceProvider)
at RP_Notify.Program.Main()

From the second log entry:
Faulting application name: RP_Notify.exe, version: 1.0.0.0, time stamp: 0xc4f713f3
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0x54734dee
Exception code: 0xe0434352

From the third  log entry:
Fault bucket 1431091245937625545, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: RP_Notify.exe
P2: 1.0.0.0
P3: c4f713f3
P4: RP_Notify
P5: 1.0.0.0
P6: c4f713f3
P7: 505
P8: 0
P9: System.NullReferenceException
P10:

**Comment by gvajda** [comment] 2020-03-04 10:22
The function throwing the error tries to read and parse the _config.ini_ file but fails to do it. There is no sign that the VPN client is involved in the error. I assume that the config file initialization fails in the first place. Please check if the following file exists after running the exe:
_c:\Users\\**yourusername**\AppData\Roaming\RP_Notify\config.ini_
If the file is missing then please try to execute the application as administrator.

**Comment by mirceat11** [comment] 2020-03-04 11:56
Fast reply on the crash:
- there is config.ini on the PC, on the expected path, having EnableLoggingToFile=true
- the VPN client has not been started
- RP_Notify v1.0 and RP_Notify v1.1 are stored into the same folder
- each one executable has been renamed as RP_Notify.exe, when running the below tests   
- 4 startup scenarios have been tested - regular run and run as admin, both from Windows Explorer and Start menu
- RP_Notify v1.1 crashes on all 4 scenarios, there is not a single entry into log.txt
- RP_Notify v1.0 starts on any scenario and writes as expected into log.txt 
The VPN client is no more a suspect, I am out of other ideas, for now.
RP_Notify v1.0 is able to read and parse the config.ini file.

**Comment by mirceat11** [comment] 2020-03-04 11:58
Sorry for mistakenly closing the issue. :)

**Comment by gvajda** [comment] 2020-03-04 12:08
Found the problem:
A new feature (Prompt user for song rating) has a new configuration entry. When the config file is missing then it's created with the default values but if a configuration value is missing then it causes an unhandled exception. In this case, the old config file is missing the entry for the added feature.

There is 2 way to solve this:
- add the line **PromptForRating=False** to the _config.ini_ file under the section **[AppSettings]**
- delete the _config.ini_ file which will re-initialize it with the default values

This bug will be fixed in the next release.

**Comment by mirceat11** [comment] 2020-03-04 12:57
The new config line does the trick. Haven't tried the second option.
Have installed VS on my local computer meantime, in order to debug the applet.
It errors on line 194, when parsing for the PromptForRating key.
Next time will be easier to locate the exception.  :)

**Comment by gvajda** [comment] 2020-03-04 13:02
Okay, thanks for reporting this, I will close this ticket.
Bugfix will follow.

**Closed as completed by gvajda** 2020-03-04 13:02 UTC

**Comment by gvajda** [comment] 2020-03-24 09:10
The issue is fixed in v1.2
